<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE testStorage [

<!ELEMENT testStorage (playlist*, audioClip*) >
<!ATTLIST testStorage tempFiles CDATA       #REQUIRED >

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #REQUIRED >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >
]>
<testStorage tempFiles="file:///tmp/tempPlaylist">
    <playlist id="1" playlength="00:00:34.000" >
        <playlistElement id="101"    relativeOffset="0" >
            <audioClip   id="10001"  playlength="00:00:11.000" 
                         uri="file:var/test10001.mp3" />
        </playlistElement>
        <playlistElement id="102"    relativeOffset="00:00:11.000000" >
            <audioClip   id="10002"  playlength="00:00:12.000000" 
                         uri="file:var/test10002.mp3" /> 
            <fadeInfo    id="9901"   fadeIn="00:00:02.000000" 
                                     fadeOut="00:00:01.500000" />
        </playlistElement>
        <playlistElement id="103"    relativeOffset="00:00:23.000000" >
            <playlist    id="2"      playlength="00:00:11.000000" > 
                <playlistElement id="111"    relativeOffset="0" >
                    <audioClip   id="10003"  playlength="00:00:11.000" 
                                 uri="file:var/test10003.mp3" />
                </playlistElement>
            </playlist>
        </playlistElement>
    </playlist>
    <playlist    id="2"      playlength="00:00:11.000000" > 
        <playlistElement id="111"    relativeOffset="0" >
            <audioClip   id="10003"  playlength="00:00:11.000" 
                            uri="file:var/test10003.mp3" />
        </playlistElement>
    </playlist>
    <audioClip id="10001" playlength="01:00:00.000" 
               uri="file:var/test10001.mp3" />
    <audioClip id="10002" playlength="00:30:00.000" 
               uri="file:var/test10002.mp3" /> 
    <audioClip id="10003" playlength="00:30:00.000" 
               uri="file:var/test10003.mp3" /> 
</testStorage>
