<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE playlist [

<!ELEMENT playlist (playlistElement*) >
<!ATTLIST playlist id           NMTOKEN     #REQUIRED >
<!ATTLIST playlist playlength   NMTOKEN     #REQUIRED >

<!ELEMENT playlistElement ((audioClip|playlist), fadeInfo?) >
<!ATTLIST playlistElement id              NMTOKEN     #REQUIRED >
<!ATTLIST playlistElement relativeOffset  NMTOKEN     #REQUIRED >

<!ELEMENT audioClip EMPTY >
<!ATTLIST audioClip id              NMTOKEN     #REQUIRED >
<!ATTLIST audioClip playlength      NMTOKEN     #REQUIRED >
<!ATTLIST audioClip uri             CDATA       #IMPLIED  >

<!ELEMENT fadeInfo EMPTY >
<!ATTLIST fadeInfo id              NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeIn          NMTOKEN     #REQUIRED >
<!ATTLIST fadeInfo fadeOut         NMTOKEN     #REQUIRED >
]>

<playlist id="1" playlength="00:00:34.000" >
    <playlistElement id="101"    relativeOffset="0" >
        <audioClip   id="10001"  playlength="00:00:11.000" 
                     uri="file:var/test1.mp3" />
    </playlistElement>
    <playlistElement id="102"    relativeOffset="00:00:11.000000" >
        <audioClip   id="10002"  playlength="00:00:12.000000" 
                     uri="file:var/test2.mp3" /> 
        <fadeInfo    id="9901"   fadeIn="00:00:02.000000" 
                                 fadeOut="00:00:01.500000" />
    </playlistElement>
    <playlistElement id="103"    relativeOffset="00:00:23.000000" >
        <playlist    id="2"      playlength="00:00:11.000000" > 
            <playlistElement id="111"    relativeOffset="0" >
                <audioClip   id="10003"  playlength="00:00:11.000" 
                             uri="file:var/test3.mp3" />
            </playlistElement>
        </playlist>
    </playlistElement>
</playlist>
